name: possystem
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^0.4.0
  cupertino_icons: ^0.1.2
  awesome_dialog: ^0.0.2
  flutter_screenutil: ^0.5.3
  
  vector_math: ^2.0.8
  font_awesome_flutter: ^8.4.0
  stepper_touch: ^0.0.1
  page_transition: ^1.1.4
  sunmi_aidl_print: ^0.0.1
  passcode_screen: ^1.0.2
  flutter_lock_screen: ^1.0.3
  giffy_dialog: ^1.6.1
  http: ^0.12.0+2
  flutter_money_formatter: ^0.8.3
  flutter_multiselect: ^0.0.1
  nice_button: ^0.1.7
  flutter_custom_dialog: ^1.0.15
  loading: ^1.0.2
  rflutter_alert: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/POS.png
  - assets/AUTHPOS.png
  - assets/t2.jpg
  - assets/sd1.jpg
  - assets/bg.jpg
  - assets/b.jpg
  - assets/b1.jpg
  - assets/bg1.jpg
  - assets/bg2.jpg
  - assets/bg3.jpg
  - assets/bg4.jpg
  - assets/bg5.jpg
  - assets/bg6.jpg
  - assets/barcode.jpg
  - assets/POSHUB.png  
  - assets/1.png
  - assets/ot.png
  - assets/ot1.png
  - assets/ot2.png
  - assets/1.jpg
  - assets/q1.jpg
  - assets/q2.png
  - assets/q3.png
  - assets/transaction.gif
  - assets/t1.gif
  - assets/eye.png
  - assets/it.gif
  - assets/prod.gif
  - assets/eye1.png
  - assets/refund1.png
  - assets/member1.png
  - assets/p1.gif
  - assets/p2.gif
  - assets/view.png
  - assets/member.png
  - assets/error.gif
  - assets/date.gif
  - assets/20.gif
  - assets/special.gif
  - assets/sp1.gif
  - assets/logout.gif
  - images/POS.png
  - assets/heart.png
  - assets/POS1.png
  - assets/POS2.png
  - assets/POS5.jpg
  - assets/POS6.png
  - assets/trans.png
  - assets/void.png
  - assets/discount.png
  - assets/clshift.png
  - assets/logout.png
  - assets/barcode.png
  - assets/bar.png
  - assets/bar1.png
  - assets/refund.png
  - assets/b2.png
  - assets/view.png
  - assets/t1.png
  - assets/t2.png
  - assets/d1.png
  - assets/d2.png
  - assets/lg1.png
  - assets/v1.png
  - assets/me1.png
  - assets/lg2.png
  - assets/cl22.png
  - assets/dis1.png
  - assets/ds2.png
  - assets/ds3.png
  - assets/lg4.png
  - assets/tran.png
  - assets/cl3.png
  - assets/mems.png
  - assets/ds6.png
  - assets/d6.png
  - assets/cartx.png
  - assets/t3.png
  - assets/t4.png
  - assets/me.png
  - assets/d7.png
  - assets/d8.png
  - assets/lg5.png
  - assets/tr1.png
  - assets/ct1.png
  - assets/dis2.png
  - assets/dis3.png
  - assets/m2.png
  - assets/cls1.png
  - assets/log1.png
  - assets/log2.png
  - assets/log3.png
  - assets/ct2.png
  - assets/person1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
